### ISSUE TITLE
REQUEST: Update site for better readability

### ISSUE THREAD

**Issue by onebree** [activeldap/activeldap.github.io#1]
When reading the tutorial, it is very difficult to follow along because in-line code samples are not highlighted. Instead, they are typed in normal sans-serif. This makes it difficult to skim through the document looking for keywords that ActiveLDAP recognizes.

Also, the font is very small, and spans nearly the entire screen. On a 20 inch monitor, it is difficult to follow a paragraph when a single sentence is nearly the width of my monitor.

Suggestion: Recreate the site with an updated feel, including a larger font and in-line code formatting.

**Comment by kou** [comment]
The document is generated by https://github.com/lsegal/yard .
Could you report it to the project? https://github.com/lsegal/yard/issues/new

Maybe, you can fix the problem by changing the https://github.com/lsegal/yard/blob/master/templates/default/fulldoc/html/css/style.css#L7 line.

**Comment by onebree** [comment]
I did not know it was generated by YARD. But like my post said, there is a lack of in-line code formatting, and I do not know if YARD supports that.

**Comment by kou** [comment]
We're using Texttile as markup language: https://github.com/activeldap/activeldap/blob/master/doc/text/tutorial.textile
Textile is one of YARD supported markup languages. Textile supports in-line code markup: https://en.wikipedia.org/wiki/Textile_%28markup_language%29#Code

**Comment by onebree** [comment]
Thank you, I will read up on it. If I find the time, I will submit a pull request.
